// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN-qOeTVRtXiPoTKsY4aUWhVjnqqtAurs',
    appId: '1:402581794004:web:9864636a23f551ba2ddf41',
    messagingSenderId: '402581794004',
    projectId: 'stealthbids-b0ef9',
    authDomain: 'stealthbids-b0ef9.firebaseapp.com',
    storageBucket: 'stealthbids-b0ef9.appspot.com',
    measurementId: 'G-CR59HLN9Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPM7hAVVg1QdcO872Dn3XzDEkLm6s1PM',
    appId: '1:402581794004:android:b0a531b748d002ee2ddf41',
    messagingSenderId: '402581794004',
    projectId: 'stealthbids-b0ef9',
    storageBucket: 'stealthbids-b0ef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9oyTHjdai_WkXx1xAOHFGKhkWzlTICIM',
    appId: '1:402581794004:ios:6577338fa80981b02ddf41',
    messagingSenderId: '402581794004',
    projectId: 'stealthbids-b0ef9',
    storageBucket: 'stealthbids-b0ef9.appspot.com',
    iosBundleId: 'com.example.stealthbids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9oyTHjdai_WkXx1xAOHFGKhkWzlTICIM',
    appId: '1:402581794004:ios:1c6d56345c5fdd832ddf41',
    messagingSenderId: '402581794004',
    projectId: 'stealthbids-b0ef9',
    storageBucket: 'stealthbids-b0ef9.appspot.com',
    iosBundleId: 'com.example.stealthbids.RunnerTests',
  );
}
